// <auto-generated />
using System;
using CadastroVeiculos.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroVeiculos.Infra.Data.Migrations
{
    [DbContext(typeof(CadastroVeiculosContext))]
    [Migration("20220621175738_CreateTableMarca")]
    partial class CreateTableMarca
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CadastroVeiculos.Domain.Entities.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tx_nome");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("nb_status");

                    b.HasKey("Id");

                    b.ToTable("marca");
                });
#pragma warning restore 612, 618
        }
    }
}
